name = "flight-monitor-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[dev]
ip = "0.0.0.0"
port = 8787

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

